# Generated by Django 3.2.7 on 2021-10-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_num', models.CharField(max_length=20)),
                ('residence', models.CharField(max_length=100)),
                ('email_alt', models.EmailField(max_length=254)),
                ('education', models.CharField(max_length=50)),
                ('hobbies', models.CharField(max_length=100)),
            ],
        ),
    ]
